In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv", encoding = "ISO-8859-1")
df.head()

Date  Label                                               Top1  \
0  2008-08-08      0  b"Georgia 'downs two Russian warplanes' as cou...   
1  2008-08-11      1  b'Why wont America and Nato help us? If they w...   
2  2008-08-12      0  b'Remember that adorable 9-year-old who sang a...   
3  2008-08-13      0  b' U.S. refuses Israel weapons to attack Iran:...   
4  2008-08-14      1  b'All the experts admit that we should legalis...   

                                                Top2  \
0            b'BREAKING: Musharraf to be impeached.'   
1        b'Bush puts foot down on Georgian conflict'   
2                 b"Russia 'ends Georgia operation'"   
3  b"When the president ordered to attack Tskhinv...   
4  b'War in South Osetia - 89 pictures made by a ...   

                                                Top3  \
0  b'Russia Today: Columns of troops roll into So...   
1  b"Jewish Georgian minister: Thanks to Israeli ...   
2  b'"If we had no sexual harassment we would hav...   
3  b' Israel clears troops who killed Reuters cam...   
4  b'Swedish wrestler Ara Abrahamian throws away ...   

                                                Top4  \
0  b'Russian tanks are moving towards the capital...   
1  b'Georgian army flees in disarray as Russians ...   
2  b"Al-Qa'eda is losing support in Iraq because ...   
3  b'Britain\'s policy of being tough on drugs is...   
4  b'Russia exaggerated the death toll in South O...   

                                                Top5  \
0  b"Afghan children raped with 'impunity,' U.N. ...   
1      b"Olympic opening ceremony fireworks 'faked'"   
2  b'Ceasefire in Georgia: Putin Outmaneuvers the...   
3  b'Body of 14 year old found in trunk; Latest (...   
4  b'Missile That Killed 9 Inside Pakistan May Ha...   

                                                Top6  \
0  b'150 Russian tanks have entered South Ossetia...   
1  b'What were the Mossad with fraudulent New Zea...   
2  b'Why Microsoft and Intel tried to kill the XO...   
3  b'China has moved 10 *million* quake survivors...   
4  b"Rushdie Condemns Random House's Refusal to P...   

                                                Top7  \
0  b"Breaking: Georgia invades South Ossetia, Rus...   
1  b'Russia angered by Israeli military sale to G...   
2  b'Stratfor: The Russo-Georgian War and the Bal...   
3  b"Bush announces Operation Get All Up In Russi...   
4  b'Poland and US agree to missle defense deal. ...   

                                                Top8  ...  \
0  b"The 'enemy combatent' trials are nothing but...  ...   
1  b'An American citizen living in S.Ossetia blam...  ...   
2  b"I'm Trying to Get a Sense of This Whole Geor...  ...   
3             b'Russian forces sink Georgian ships '  ...   
4  b'Will the Russians conquer Tblisi? Bet on it,...  ...   

                                               Top16  \
0  b'Georgia Invades South Ossetia - if Russia ge...   
1  b'Israel and the US behind the Georgian aggres...   
2  b'U.S. troops still in Georgia (did you know t...   
3                      b'Elephants extinct by 2020?'   
4  b'Bank analyst forecast Georgian crisis 2 days...   

                                               Top17  \
0                b'Al-Qaeda Faces Islamist Backlash'   
1  b'"Do not believe TV, neither Russian nor Geor...   
2       b'Why Russias response to Georgia was right'   
3  b'US humanitarian missions soon in Georgia - i...   
4  b"Georgia confict could set back Russia's US r...   

                                               Top18  \
0  b'Condoleezza Rice: "The US would not act to p...   
1  b'Riots are still going on in Montreal (Canada...   
2  b'Gorbachev accuses U.S. of making a "serious ...   
3             b"Georgia's DDOS came from US sources"   
4  b'War in the Caucasus is as much the product o...   

                                               Top19  \
0  b'This is a busy day:  The European Union has ...   
1    b'China to overtake US as largest manufac

#### Preprocessing the data

In [3]:
df.columns

Index(['Date', 'Label', 'Top1', 'Top2', 'Top3', 'Top4', 'Top5', 'Top6', 'Top7',
       'Top8', 'Top9', 'Top10', 'Top11', 'Top12', 'Top13', 'Top14', 'Top15',
       'Top16', 'Top17', 'Top18', 'Top19', 'Top20', 'Top21', 'Top22', 'Top23',
       'Top24', 'Top25'],
      dtype='object')

In [4]:
#Converting to lower case from column 2 to 27
for col in df.columns[2:27]:
    df[col] = df[col].str.lower()
df.head(3)

Date  Label                                               Top1  \
0  2008-08-08      0  b"georgia 'downs two russian warplanes' as cou...   
1  2008-08-11      1  b'why wont america and nato help us? if they w...   
2  2008-08-12      0  b'remember that adorable 9-year-old who sang a...   

                                          Top2  \
0      b'breaking: musharraf to be impeached.'   
1  b'bush puts foot down on georgian conflict'   
2           b"russia 'ends georgia operation'"   

                                                Top3  \
0  b'russia today: columns of troops roll into so...   
1  b"jewish georgian minister: thanks to israeli ...   
2  b'"if we had no sexual harassment we would hav...   

                                                Top4  \
0  b'russian tanks are moving towards the capital...   
1  b'georgian army flees in disarray as russians ...   
2  b"al-qa'eda is losing support in iraq because ...   

                                                Top5  \
0  b"afghan children raped with 'impunity,' u.n. ...   
1      b"olympic opening ceremony fireworks 'faked'"   
2  b'ceasefire in georgia: putin outmaneuvers the...   

                                                Top6  \
0  b'150 russian tanks have entered south ossetia...   
1  b'what were the mossad with fraudulent new zea...   
2  b'why microsoft and intel tried to kill the xo...   

                                                Top7  \
0  b"breaking: georgia invades south ossetia, rus...   
1  b'russia angered by israeli military sale to g...   
2  b'stratfor: the russo-georgian war and the bal...   

                                                Top8  ...  \
0  b"the 'enemy combatent' trials are nothing but...  ...   
1  b'an american citizen living in s.ossetia blam...  ...   
2  b"i'm trying to get a sense of this whole geor...  ...   

                                               Top16  \
0  b'georgia invades south ossetia - if russia ge...   
1  b'israel and the us behind the georgian aggres...   
2  b'u.s. troops still in georgia (did you know t...   

                                               Top17  \
0                b'al-qaeda faces islamist backlash'   
1  b'"do not believe tv, neither russian nor geor...   
2       b'why russias response to georgia was right'   

                                               Top18  \
0  b'condoleezza rice: "the us would not act to p...   
1  b'riots are still going on in montreal (canada...   
2  b'gorbachev accuses u.s. of making a "serious ...   

                                               Top19  \
0  b'this is a busy day:  the european union has ...   
1    b'china to overtake us as largest manufacturer'   
2         b'russia, georgia, and nato: cold war two'   

                                               Top20  \
0  b"georgia will withdraw 1,000 soldiers from ir...   
1                     b'war in south ossetia [pics]'   
2  b'remember that adorable 62-year-old who led y...   

                                               Top21  \
0  b'why the pentagon thinks attacking iran is a ...   
1  b'israeli physicians group condemns state tort...   
2          b'war in georgia: the israeli connection'   

                                               Top22  \
0  b'caucasus in crisis: georgia invades south os...   
1  b' russia has just beaten the united states ov...   
2  b'all signs point to the us encouraging georgi...   

                                               Top23  \
0  b'indian shoe manufactory  - and again in a se...   
1  b'perhaps *the* question about the georgia - r...   
2  b'christopher king argues that the us and nato...   

                                               Top24  \
0  b'visitors suffering from mental illnesses ban...   
1                 b'russia is so much better at war'   
2                        b'america: the new mexico?'   

                                               Top25  
0           b"no help for mexico's kidnapping surge"  
1 

In [5]:
#Removing the punctuations
df.replace(r"[^a-zA-Z0-9]", " ", regex= True, inplace = True)
df.head(2)   

Date  Label                                               Top1  \
0  2008 08 08      0  b georgia  downs two russian warplanes  as cou...   
1  2008 08 11      1  b why wont america and nato help us  if they w...   

                                          Top2  \
0      b breaking  musharraf to be impeached     
1  b bush puts foot down on georgian conflict    

                                                Top3  \
0  b russia today  columns of troops roll into so...   
1  b jewish georgian minister  thanks to israeli ...   

                                                Top4  \
0  b russian tanks are moving towards the capital...   
1  b georgian army flees in disarray as russians ...   

                                                Top5  \
0  b afghan children raped with  impunity   u n  ...   
1      b olympic opening ceremony fireworks  faked     

                                                Top6  \
0  b 150 russian tanks have entered south ossetia...   
1  b what were the mossad with fraudulent new zea...   

                                                Top7  \
0  b breaking  georgia invades south ossetia  rus...   
1  b russia angered by israeli military sale to g...   

                                                Top8  ...  \
0  b the  enemy combatent  trials are nothing but...  ...   
1  b an american citizen living in s ossetia blam...  ...   

                                               Top16  \
0  b georgia invades south ossetia   if russia ge...   
1  b israel and the us behind the georgian aggres...   

                                               Top17  \
0                b al qaeda faces islamist backlash    
1  b  do not believe tv  neither russian nor geor...   

                                               Top18  \
0  b condoleezza rice   the us would not act to p...   
1  b riots are still going on in montreal  canada...   

                                               Top19  \
0  b this is a busy day   the european union has ...   
1    b china to overtake us as largest manufacturer    

                                               Top20  \
0  b georgia will withdraw 1 000 soldiers from ir...   
1                     b war in south ossetia  pics     

                                               Top21  \
0  b why the pentagon thinks attacking iran is a ...   
1  b israeli physicians group condemns state tort...   

                                               Top22  \
0  b caucasus in crisis  georgia invades south os...   
1  b  russia has just beaten the united states ov...   

                                               Top23  \
0  b indian shoe manufactory    and again in a se...   
1  b perhaps  the  question about the georgia   r...   

                                               Top24  \
0  b visitors suffering from mental illnesses ban...   
1                 b russia is so much better at war    

                                               Top25  
0           b no help for mexico s kidnapping surge   
1  b so this is what it s come to  trading sex fo...  

[2 rows x 27 columns]

In [6]:
df.shape

(1989, 27)

In [7]:
#Join the entire news of a row from column 2 to 27
headlines=[]
for row in range(df.shape[0]):
    headlines.append("".join(str(x) for x in df.iloc[row, 2:27]))

In [8]:
#check a headline
headlines[1]

'b why wont america and nato help us  if they wont help us now  why did we help them in iraq  b bush puts foot down on georgian conflict b jewish georgian minister  thanks to israeli training  we re fending off russia  b georgian army flees in disarray as russians advance   gori abandoned to russia without a shot fired b olympic opening ceremony fireworks  faked  b what were the mossad with fraudulent new zealand passports doing in iraq  b russia angered by israeli military sale to georgia b an american citizen living in s ossetia blames u s  and georgian leaders for the genocide of innocent people b welcome to world war iv  now in high definition  b georgia s move  a mistake of monumental proportions  b russia presses deeper into georgia  u s  says regime change is goal b abhinav bindra wins first ever individual olympic gold medal for india b  u s  ship heads for arctic to define territory b drivers in a jerusalem taxi station threaten to quit rather than work for their new boss   an

In [9]:
#create a new dataset with all the headlines combined with its dates and labels
d = {"date":df["Date"],"Label": df["Label"], "headlines": headlines}
df1 = pd.DataFrame(data= d)
df1.head()

date  Label                                          headlines
0  2008 08 08      0  b georgia  downs two russian warplanes  as cou...
1  2008 08 11      1  b why wont america and nato help us  if they w...
2  2008 08 12      0  b remember that adorable 9 year old who sang a...
3  2008 08 13      0  b  u s  refuses israel weapons to attack iran ...
4  2008 08 14      1  b all the experts admit that we should legalis...

In [10]:
#convert string date to time date format
df1["date"] = pd.to_datetime(df1["date"])
df1["date"]

0      2008-08-08
1      2008-08-11
2      2008-08-12
3      2008-08-13
4      2008-08-14
          ...    
1984   2016-06-27
1985   2016-06-28
1986   2016-06-29
1987   2016-06-30
1988   2016-07-01
Name: date, Length: 1989, dtype: datetime64[ns]

In [11]:
#Divide the dataset into train and test by its date
#Train dataset- till 2014
#Test dataset - from 2015
df_train = df1[df1["date"] < "2015-01-01"]
df_test = df1[df1["date"] > "2014-12-31"]

In [12]:
#check the datasets
df_train.head(), df_test.head()

(        date  Label                                          headlines
 0 2008-08-08      0  b georgia  downs two russian warplanes  as cou...
 1 2008-08-11      1  b why wont america and nato help us  if they w...
 2 2008-08-12      0  b remember that adorable 9 year old who sang a...
 3 2008-08-13      0  b  u s  refuses israel weapons to attack iran ...
 4 2008-08-14      1  b all the experts admit that we should legalis...,
            date  Label                                          headlines
 1611 2015-01-02      1  most cases of cancer are the result of sheer b...
 1612 2015-01-05      0  moscow  gt beijing high speed train will reduc...
 1613 2015-01-06      0  us oil falls below  50 a barreltoyota gives aw...
 1614 2015-01-07      1   shots fired  at french magazine hq90  of bibi...
 1615 2015-01-08      1  new charlie hebdo issue to come out next week ...)

In [13]:
#length of each dataset
print("length of training dataset:",len(df_train)) 
print("length of testing dataset:",len(df_test))

length of training dataset: 1611
length of testing dataset: 378


## Feature Extraction

#### Use CountVectorizer and RandomForestClassifier

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier

In [15]:
#implement BOW
countvector = CountVectorizer(ngram_range=(2,2)) #bigrams
train_dataset = countvector.fit_transform(df_train["headlines"])
train_dataset

<1611x371577 sparse matrix of type '<class 'numpy.int64'>'
	with 662785 stored elements in Compressed Sparse Row format>

In [16]:
#Implement Random Forest Classification with x= traindataset and y = df_train["Label"] 
RFClassifier = RandomForestClassifier(n_estimators=200,criterion= "entropy")
RFClassifier.fit(train_dataset,df_train["Label"] )

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [17]:
#Predict Test Dataset
test_dataset = countvector.transform(df_test["headlines"])
test_dataset

<378x371577 sparse matrix of type '<class 'numpy.int64'>'
	with 80281 stored elements in Compressed Sparse Row format>

In [18]:
predictions = RFClassifier.predict(test_dataset)
predictions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [19]:
#Import libraries to check accuracy
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [20]:
accuracy_score(df_test["Label"], predictions)

0.5079365079365079

In [21]:
confusion_matrix(df_test["Label"],predictions)

array([[  3, 183],
       [  3, 189]], dtype=int64)

In [22]:
print(classification_report(df_test["Label"],predictions))

              precision    recall  f1-score   support

           0       0.50      0.02      0.03       186
           1       0.51      0.98      0.67       192

    accuracy                           0.51       378
   macro avg       0.50      0.50      0.35       378
weighted avg       0.50      0.51      0.36       378



#### Lets use TFIDF instead of Count Vectorizer

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [24]:
TfidfVector = TfidfVectorizer(ngram_range=(2,2))
train_dataset1 = TfidfVector.fit_transform(df_train["headlines"])

In [25]:
#Implement Random Forest Classification with x= traindataset and y = df_train["Label"] 
RFClassifier1 = RandomForestClassifier(n_estimators=200,criterion= "entropy")
RFClassifier1.fit(train_dataset1,df_train["Label"] )

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [26]:
#Predict Test Dataset
test_dataset1 = TfidfVector.transform(df_test["headlines"])
test_dataset1

<378x371577 sparse matrix of type '<class 'numpy.float64'>'
	with 80281 stored elements in Compressed Sparse Row format>

In [27]:
predictions1 = RFClassifier.predict(test_dataset1)
predictions1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [28]:
accuracy_score(df_test["Label"],predictions1)

0.5079365079365079

In [29]:
confusion_matrix(df_test["Label"], predictions1)

array([[  0, 186],
       [  0, 192]], dtype=int64)

In [30]:
print(classification_report(df_test["Label"],predictions1))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       186
           1       0.51      1.00      0.67       192

    accuracy                           0.51       378
   macro avg       0.25      0.50      0.34       378
weighted avg       0.26      0.51      0.34       378



C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#### Lets use Navie bayes instead of RandomForest

In [31]:
from sklearn.naive_bayes import MultinomialNB

In [32]:
naive = MultinomialNB()
naive.fit(train_dataset,df_train["Label"])

MultinomialNB()

In [33]:
predictions2= naive.predict(test_dataset)
predictions2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [34]:
confusion_matrix(df_test['Label'], predictions2)

array([[ 18, 168],
       [ 25, 167]], dtype=int64)

In [35]:
accuracy_score(df_test['Label'], predictions2)

0.4894179894179894

In [36]:
print(classification_report(df_test['Label'], predictions2))

              precision    recall  f1-score   support

           0       0.42      0.10      0.16       186
           1       0.50      0.87      0.63       192

    accuracy                           0.49       378
   macro avg       0.46      0.48      0.40       378
weighted avg       0.46      0.49      0.40       378



#### All the algorithms have the same accuracy score which is 50%